# Dockerfile

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build
# RUN npm install -g next

ARG NEXT_PUBLIC_PARSE_APPLICATION_ID=''
ARG NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY=''

ENV NEXT_PUBLIC_PARSE_APPLICATION_ID=$NEXT_PUBLIC_PARSE_APPLICATION_ID
ENV NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY=$NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY

EXPOSE 3000

CMD ["npm", "run", "start"]

RUN echo "Environment Variables:"
RUN printenv NEXT_PUBLIC_PARSE_APPLICATION_ID
RUN printenv NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY